spring:
  application:
    name: user-service
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    username: anvarzhonov
    password: anvarzhonov
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/safe_rental_db


eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka}

server:
  port: ${SERVER_PORT:9095}
